### ISSUE TITLE
Observed a panic: "index out of range" (runtime error: index out of range)

### ISSUE THREAD

**Issue by WenlinH** [Dynatrace/dynatrace-oneagent-operator#68]
Successfully deployed the Dynatrace OneAgent operator and created a secret called oneagent that contained both the PaaS and API  tokens. I then updated the example CR to include the environment ID from my free trial account. 

The following contains the logs from the operator being deployed and the error that occurred after applying the CR:
```
{"level":"info","ts":1548881158.6203792,"logger":"cmd","msg":"Go Version: go1.10.8"}
{"level":"info","ts":1548881158.620456,"logger":"cmd","msg":"Go OS/Arch: linux/amd64"}
{"level":"info","ts":1548881158.620492,"logger":"cmd","msg":"Version of operator-sdk: v0.4.0"}
{"level":"info","ts":1548881158.6205025,"logger":"cmd","msg":"Version of dynatrace-oneagent-operator: snapshot"}
{"level":"info","ts":1548881158.620813,"logger":"leader","msg":"Trying to become the leader."}
{"level":"info","ts":1548881159.221165,"logger":"leader","msg":"Found existing lock with my name. I was likely restarted."}
{"level":"info","ts":1548881159.22122,"logger":"leader","msg":"Continuing as the leader."}
{"level":"info","ts":1548881159.6219733,"logger":"cmd","msg":"Registering Components."}
{"level":"info","ts":1548881160.022149,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"oneagent-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1548881160.0223534,"logger":"kubebuilder.controller","msg":"Starting EventSource","controller":"oneagent-controller","source":"kind source: /, Kind="}
{"level":"info","ts":1548881160.0225244,"logger":"cmd","msg":"Starting the Cmd."}
{"level":"info","ts":1548881160.1228242,"logger":"kubebuilder.controller","msg":"Starting Controller","controller":"oneagent-controller"}
{"level":"info","ts":1548881160.2231073,"logger":"kubebuilder.controller","msg":"Starting workers","controller":"oneagent-controller","worker count":1}
{"level":"info","ts":1548881160.2232509,"logger":"oneagent.controller","msg":"reconciling oneagent","namespace":"dynatrace","name":"oneagent"}
E0130 20:46:00.230112       1 runtime.go:66] Observed a panic: "index out of range" (runtime error: index out of range)
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:72
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/asm_amd64.s:573
/usr/local/go/src/runtime/panic.go:502
/usr/local/go/src/runtime/panic.go:28
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent/oneagent_controller.go:171
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent/oneagent_controller.go:133
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:213
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134
/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/usr/local/go/src/runtime/asm_amd64.s:2361
panic: runtime error: index out of range [recovered]
	panic: runtime error: index out of range

goroutine 497 [running]:
github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x107
panic(0x10f9220, 0x1b57d90)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent.(*ReconcileOneAgent).reconcileRollout(0xc420512480, 0x1369dc0, 0xc42059d8e0, 0xc42048ae00, 0x9, 0xc42003fc70, 0x8)
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent/oneagent_controller.go:171 +0x774
github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent.(*ReconcileOneAgent).Reconcile(0xc420512480, 0xc42003fcf0, 0x9, 0xc42003fc70, 0x8, 0x1b6b040, 0x40d, 0x0, 0xc420474d30)
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/pkg/controller/oneagent/oneagent_controller.go:133 +0x4b6
github.com/Dynatrace/dynatrace-oneagent-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc4200d6140, 0x0)
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:213 +0x1c6
github.com/Dynatrace/dynatrace-oneagent-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1()
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:158 +0x36
github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc420307640)
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc420307640, 0x3b9aca00, 0x0, 0xc400000001, 0xc4203780c0)
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbd
github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc420307640, 0x3b9aca00, 0xc4203780c0)
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by github.com/Dynatrace/dynatrace-oneagent-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start
	/go/src/github.com/Dynatrace/dynatrace-oneagent-operator/vendor/sigs.k8s.io/controller-runtime/pkg/internal/controller/controller.go:157 +0x35b
```

Did I miss a step? I can't seem to identify anything that went wrong.

**Comment by baichinger** [comment]
Hi @jeremylinlin! You run into a bug which we are currently working on. Please use `v0.2.0` (https://github.com/Dynatrace/dynatrace-oneagent-operator/tree/v0.2.0) for the time being.

**Comment by lrgar** [comment]
This was found on the dev snapshots I believe, and been fixed since then.
